name: E2E on Chrome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          run: |
           yarn cy:run:report
           yarn mocha:merge:json
           yarn mocha:merge:html
          
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: report/screenshots

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: report-files
          path: report/
      
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: html-report
          path: mochawesome-report/
